### ISSUE TITLE
Breaks kirbytext/markdown when adding plugin.kirby-highlight.languages config

### ISSUE THREAD

**Issue by fitzage** [S1SYPHOS/kirby-highlight#2]
Am I doing something wrong here? I added this to my config, and none of the kirbytext and markdown on pages with code blocks gets parsed anymore. Removing the line fixes it.

```
c::set('plugin.kirby-highlight.languages', ['html','php','json','bash','shell','javascript','apache','java','cpp','cs','css','http','makefile','markdown','nginx','objectivec','perl','python','ruby','go']);
```

**Comment by daybugging** [comment]
Have you tried `array('option1', 'option2', optionN)` instead of `[brackets]` just to be sure?

**Comment by fitzage** [comment]
Yes, this gives me the same result:

```
c::set('plugin.kirby-highlight.languages', array('html', 'php', 'json', 'bash', 'shell', 'javascript', 'apache', 'java', 'cpp', 'cs', 'css', 'http', 'makefile', 'markdown', 'nginx', 'objectivec', 'perl', 'python', 'ruby', 'go'));
```

**Comment by S1SYPHOS** [comment]
@daybugging: That's nonsense, since this represents still a valid array - but `'shell'` is no supported language. See https://github.com/S1SYPHOS/kirby-highlight/tree/master/vendor/scrivo/highlight.php/Highlight/languages

Removing this should work.

**Comment by fitzage** [comment]
Ah, well removing shell fixed it. I didn't find the list, so I was just going by what I found on the highlight.js site. Thanks!

**Comment by S1SYPHOS** [comment]
Well, since `highlight.php` is a tad bit outdated (maybe I'll add some language definitions in the future), they don't support the exact same range of languages.

Edit: Will put something in the README, like "Troubleshooting" or something!

**Comment by S1SYPHOS** [comment]
@fitzage: I added more languages (and styles), among them `shell`, so if you'd like to try it, be my guest!

**Comment by fitzage** [comment]
Yes, I was able to re-add shell and have it not break anything.

Maybe there should be a check so that if someone like me foolishly puts a non-existant language in there that it will just dump it instead of failing.
